2016-05-30 15:41:24,909 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 626, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'BlockingIOError: [Errno 11] Resource temporarily unavailable\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 626, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'KeyboardInterrupt\n']
2016-05-30 15:42:02,441 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 254, in PrepareSocket\n    UDPSocket.bind(UDPaddr)\n', 'TypeError: string or unicode text buffer expected, not NoneType\n']
2016-05-30 16:00:04,421 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 323, in PrepareMessage\n    logging.debug("Preparing Message for :" + destination)\n', "TypeError: Can't convert 'c_byte_Array_4' object to str implicitly\n"]
2016-05-30 16:00:04,424 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 548, in ChunkMessages\n    header.hop_count)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 323, in PrepareMessage\n    logging.debug("Preparing Message for :" + destination)\n', "TypeError: Can't convert 'c_byte_Array_4' object to str implicitly\n"]
2016-05-30 16:00:43,630 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 528, in Send_Message\n    logging.debug("Sent to: " + addr[0] +"=>" + addr[1])\n', "TypeError: Can't convert 'int' object to str implicitly\n"]
2016-05-30 16:00:44,402 - root - ERROR - Couldn't send messages...
2016-05-30 16:06:43,289 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 323, in PrepareMessage\n    logging.debug("Preparing Message for :" + bytearray(destination).hex().upper())\n', "TypeError: Can't convert 'c_byte_Array_4' object to str implicitly\n"]
2016-05-30 16:06:43,293 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 548, in ChunkMessages\n    header.hop_count)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 323, in PrepareMessage\n    logging.debug("Preparing Message for :" + bytearray(destination).hex().upper())\n', "TypeError: Can't convert 'c_byte_Array_4' object to str implicitly\n"]
2016-05-30 16:06:43,297 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 528, in Send_Message\n    logging.debug("Sent to: " + addr[0] +"=>" + addr[1])\n', "TypeError: Can't convert 'int' object to str implicitly\n"]
2016-05-30 16:06:43,299 - root - ERROR - Couldn't send messages...
2016-05-30 16:06:49,616 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 632, in recv_flag\n    pass\n', 'KeyboardInterrupt\n']
2016-05-30 16:08:52,912 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 563, in ChunkMessages\n    logging.debug("Chunking completed with:" + len(MessageList) + "Packets.")\n', "TypeError: Can't convert 'int' object to str implicitly\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 523, in Send_Message\n    messagetosend = ChunkMessages(payload, header)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 567, in ChunkMessages\n    logging.error(repr(traceback.format_exception(exc_type, exc_value,\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 567, in ChunkMessages\n    logging.error(repr(traceback.format_exception(exc_type, exc_value,\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 602, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n']
2016-05-30 16:08:52,913 - root - ERROR - Couldn't send messages...
2016-05-30 16:09:01,029 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 229, in Get_Port\n    temp = input(\'>>Port Number: \')\n', 'KeyboardInterrupt\n']
2016-05-30 16:10:52,672 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 528, in Send_Message\n    logging.debug("Sent to: " + addr[0] +"=>" + addr[1])\n', "TypeError: Can't convert 'int' object to str implicitly\n"]
2016-05-30 16:10:52,944 - root - ERROR - Couldn't send messages...
2016-05-30 16:17:06,472 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 835, in Add_KeyIDTable\n    username = input(\'Enter Username for this IP>>\')\n', 'KeyboardInterrupt\n']
2016-05-30 16:19:39,934 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 838, in Add_KeyIDTable\n    logging.debug(keyID_newline + "has been added to KeyID Table...")\n', "TypeError: unsupported operand type(s) for +: 'dict' and 'str'\n"]
2016-05-30 16:24:37,588 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'BlockingIOError: [Errno 11] Resource temporarily unavailable\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'KeyboardInterrupt\n']
2016-05-30 16:25:57,760 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'BlockingIOError: [Errno 11] Resource temporarily unavailable\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'KeyboardInterrupt\n']
2016-05-30 16:32:34,597 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 229, in Get_Port\n    temp = input(\'>>Port Number: \')\n', 'KeyboardInterrupt\n']
2016-05-30 16:38:16,444 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 435, in PGPEncMsg\n    encrypted_challenge = gpg.encrypt(challenge, rec_id).data\n', "NameError: name 'gpg' is not defined\n"]
2016-05-30 16:38:16,449 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 420, in PrepareAuthenticationPayload\n    AuthMessagetoSend, challenge = PGPEncMsg(rec_id, myPP)\n', "TypeError: 'NoneType' object is not iterable\n"]
2016-05-30 16:43:04,657 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 435, in PGPEncMsg\n    encrypted_challenge = gpg.encrypt(challenge, rec_id).data\n', "NameError: name 'gpg' is not defined\n"]
2016-05-30 16:43:04,659 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 420, in PrepareAuthenticationPayload\n    AuthMessagetoSend, challenge = PGPEncMsg(rec_id, myPP)\n', "TypeError: 'NoneType' object is not iterable\n"]
2016-05-30 16:43:33,384 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 621, in recv_flag\n    if total_data and Unpack(MessageClass, total_data[-1]).flag == 17 and time.time()-begin>timeout:\n', 'KeyboardInterrupt\n']
2016-05-30 16:47:05,135 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 435, in PGPEncMsg\n    encrypted_challenge = gpg.encrypt(challenge, rec_id).data\n', "NameError: name 'gpg' is not defined\n"]
2016-05-30 16:47:05,140 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 420, in PrepareAuthenticationPayload\n    AuthMessagetoSend, challenge = PGPEncMsg(rec_id, myPP)\n', "TypeError: 'NoneType' object is not iterable\n"]
2016-05-30 16:51:32,619 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'BlockingIOError: [Errno 11] Resource temporarily unavailable\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'KeyboardInterrupt\n']
2016-05-30 16:53:15,838 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 436, in PGPEncMsg\n    encrypted_challenge = gpg.encrypt(challenge, rec_id).data\n', "AttributeError: 'NoneType' object has no attribute 'encrypt'\n"]
2016-05-30 16:53:15,840 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 420, in PrepareAuthenticationPayload\n    AuthMessagetoSend, challenge = PGPEncMsg(rec_id, myPP)\n', "TypeError: 'NoneType' object is not iterable\n"]
2016-05-30 16:53:51,702 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 623, in recv_flag\n    if total_data and Unpack(MessageClass, total_data[-1]).flag == 17 and time.time()-begin>timeout:\n', 'KeyboardInterrupt\n']
2016-05-30 16:57:52,727 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 433, in PGPEncMsg\n    logging.info("PGP Challenge Encryption Process started...")\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 433, in PGPEncMsg\n    logging.info("PGP Challenge Encryption Process started...")\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 492, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n']
2016-05-30 16:57:52,728 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 420, in PrepareAuthenticationPayload\n    AuthMessagetoSend, challenge = PGPEncMsg(rec_id, myPP)\n', "TypeError: 'NoneType' object is not iterable\n"]
2016-05-30 17:13:27,087 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'BlockingIOError: [Errno 11] Resource temporarily unavailable\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'KeyboardInterrupt\n']
2016-05-30 17:22:57,945 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'BlockingIOError: [Errno 11] Resource temporarily unavailable\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'KeyboardInterrupt\n']
2016-05-30 17:26:05,973 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 433, in PGPEncMsg\n    logging.info("PGP Challenge Encryption Process started...")\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 433, in PGPEncMsg\n    logging.info("PGP Challenge Encryption Process started...")\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 492, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n']
2016-05-30 17:26:05,974 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 420, in PrepareAuthenticationPayload\n    AuthMessagetoSend, challenge = PGPEncMsg(rec_id, myPP)\n', "TypeError: 'NoneType' object is not iterable\n"]
2016-05-30 17:37:30,094 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'BlockingIOError: [Errno 11] Resource temporarily unavailable\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'KeyboardInterrupt\n']
2016-05-30 17:45:29,027 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'BlockingIOError: [Errno 11] Resource temporarily unavailable\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'KeyboardInterrupt\n']
2016-05-30 17:50:29,740 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 168, in AESDecMSg\n    decipher = AES.new(Aeskey, AES.MODE_CBC, iv)\n', '  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/AES.py", line 260, in new\n    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)\n', '  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/__init__.py", line 130, in _create_cipher\n    return modes[mode](factory, **kwargs)\n', '  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/_mode_cbc.py", line 247, in _create_cbc_cipher\n    return CbcMode(cipher_state, iv)\n', '  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/_mode_cbc.py", line 101, in __init__\n    % result)\n', 'ValueError: Error 65537 while instatiating the CBC mode\n']
2016-05-30 17:50:29,743 - root - ERROR - 
Variables CB59737D,b'selam'
2016-05-30 17:50:29,747 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 593, in ConcatMessages\n    Final_Text = Final_Text + str(AESDecMSg(message.source,message.payload), \'utf-8\')\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 168, in AESDecMSg\n    decipher = AES.new(Aeskey, AES.MODE_CBC, iv)\n', '  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/AES.py", line 260, in new\n    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)\n', '  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/__init__.py", line 130, in _create_cipher\n    return modes[mode](factory, **kwargs)\n', '  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/_mode_cbc.py", line 247, in _create_cbc_cipher\n    return CbcMode(cipher_state, iv)\n', '  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/_mode_cbc.py", line 101, in __init__\n    % result)\n', 'ValueError: Error 65537 while instatiating the CBC mode\n']
2016-05-30 17:53:06,966 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 335, in PrepareMessage\n    if type == MessageTypes.Data.value and ( Message.flag == 4 or Message.flag == 5 or Message.flag == 8 or Message.flag == 9):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 335, in PrepareMessage\n    if type == MessageTypes.Data.value and ( Message.flag == 4 or Message.flag == 5 or Message.flag == 8 or Message.flag == 9):\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 492, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n']
2016-05-30 17:53:06,967 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 558, in ChunkMessages\n    header_flag.int, chunks, header.hop_count)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 335, in PrepareMessage\n    if type == MessageTypes.Data.value and ( Message.flag == 4 or Message.flag == 5 or Message.flag == 8 or Message.flag == 9):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 335, in PrepareMessage\n    if type == MessageTypes.Data.value and ( Message.flag == 4 or Message.flag == 5 or Message.flag == 8 or Message.flag == 9):\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 492, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n']
2016-05-30 17:58:17,133 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 145, in AESEncMSg\n    AESkey,iv = Prepare_EncryptionVariables(receiver_UUID)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 124, in Prepare_EncryptionVariables\n    logging.Info("Preparing Encryption Variables for :" + receiver_UUID)\n', "AttributeError: module 'logging' has no attribute 'Info'\n"]
2016-05-30 17:58:17,135 - root - ERROR - Variables deneme deneme,CB59737D
2016-05-30 17:58:17,138 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 336, in PrepareMessage\n    payload = AESEncMSg(payload, Message.destination)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 145, in AESEncMSg\n    AESkey,iv = Prepare_EncryptionVariables(receiver_UUID)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 124, in Prepare_EncryptionVariables\n    logging.Info("Preparing Encryption Variables for :" + receiver_UUID)\n', "AttributeError: module 'logging' has no attribute 'Info'\n"]
2016-05-30 17:58:17,141 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 558, in ChunkMessages\n    header_flag.int, chunks, header.hop_count)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 336, in PrepareMessage\n    payload = AESEncMSg(payload, Message.destination)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 145, in AESEncMSg\n    AESkey,iv = Prepare_EncryptionVariables(receiver_UUID)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 124, in Prepare_EncryptionVariables\n    logging.Info("Preparing Encryption Variables for :" + receiver_UUID)\n', "AttributeError: module 'logging' has no attribute 'Info'\n"]
2016-05-30 17:59:22,742 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 145, in AESEncMSg\n    AESkey,iv = Prepare_EncryptionVariables(receiver_UUID)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 124, in Prepare_EncryptionVariables\n    logging.Info("Preparing Encryption Variables for :" + receiver_UUID)\n', "AttributeError: module 'logging' has no attribute 'Info'\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 336, in PrepareMessage\n    payload = AESEncMSg(payload, Message.destination)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 153, in AESEncMSg\n    logging.error(repr(traceback.format_exception(exc_type, exc_value,\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 153, in AESEncMSg\n    logging.error(repr(traceback.format_exception(exc_type, exc_value,\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 602, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n']
2016-05-30 17:59:22,744 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 145, in AESEncMSg\n    AESkey,iv = Prepare_EncryptionVariables(receiver_UUID)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 124, in Prepare_EncryptionVariables\n    logging.Info("Preparing Encryption Variables for :" + receiver_UUID)\n', "AttributeError: module 'logging' has no attribute 'Info'\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 558, in ChunkMessages\n    header_flag.int, chunks, header.hop_count)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 336, in PrepareMessage\n    payload = AESEncMSg(payload, Message.destination)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 153, in AESEncMSg\n    logging.error(repr(traceback.format_exception(exc_type, exc_value,\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 153, in AESEncMSg\n    logging.error(repr(traceback.format_exception(exc_type, exc_value,\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 602, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n']
2016-05-30 18:02:57,353 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', "TypeError: Can't convert 'bytes' object to str implicitly\n"]
2016-05-30 18:04:12,305 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', "TypeError: Can't convert 'bytes' object to str implicitly\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 146, in AESEncMSg\n    padMsg = padStr(bytes(plainMsg, \'utf-8\'))\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 105, in padStr\n    logging.error("Variables : " + str)\n', "TypeError: Can't convert 'bytes' object to str implicitly\n"]
2016-05-30 18:04:12,308 - root - ERROR - Variables deneme deneme,CB59737D
2016-05-30 18:04:12,314 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', "TypeError: Can't convert 'bytes' object to str implicitly\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 336, in PrepareMessage\n    payload = AESEncMSg(payload, Message.destination)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 146, in AESEncMSg\n    padMsg = padStr(bytes(plainMsg, \'utf-8\'))\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 105, in padStr\n    logging.error("Variables : " + str)\n', "TypeError: Can't convert 'bytes' object to str implicitly\n"]
2016-05-30 18:04:12,319 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', "TypeError: Can't convert 'bytes' object to str implicitly\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 558, in ChunkMessages\n    header_flag.int, chunks, header.hop_count)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 336, in PrepareMessage\n    payload = AESEncMSg(payload, Message.destination)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 146, in AESEncMSg\n    padMsg = padStr(bytes(plainMsg, \'utf-8\'))\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 105, in padStr\n    logging.error("Variables : " + str)\n', "TypeError: Can't convert 'bytes' object to str implicitly\n"]
2016-05-30 18:08:26,166 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 492, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n']
2016-05-30 18:08:26,168 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 492, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 146, in AESEncMSg\n    padMsg = padStr(bytes(plainMsg, \'utf-8\'))\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 105, in padStr\n    logging.error("Variables : " + str)\n', "TypeError: Can't convert 'bytes' object to str implicitly\n"]
2016-05-30 18:08:26,170 - root - ERROR - Variables deneme deneme,CB59737D
2016-05-30 18:08:26,171 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 492, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 336, in PrepareMessage\n    payload = AESEncMSg(payload, Message.destination)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 146, in AESEncMSg\n    padMsg = padStr(bytes(plainMsg, \'utf-8\'))\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 105, in padStr\n    logging.error("Variables : " + str)\n', "TypeError: Can't convert 'bytes' object to str implicitly\n"]
2016-05-30 18:08:26,174 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 97, in padStr\n    logging.debug("Padding string : " + str)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 492, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 558, in ChunkMessages\n    header_flag.int, chunks, header.hop_count)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 336, in PrepareMessage\n    payload = AESEncMSg(payload, Message.destination)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 146, in AESEncMSg\n    padMsg = padStr(bytes(plainMsg, \'utf-8\'))\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 105, in padStr\n    logging.error("Variables : " + str)\n', "TypeError: Can't convert 'bytes' object to str implicitly\n"]
2016-05-30 18:13:46,204 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 745, in Send_RoutingTable\n    destination = input(\'>>Destination: \')\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 745, in Send_RoutingTable\n    destination = input(\'>>Destination: \')\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 602, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n']
