2016-05-30 15:41:14,468 - root - INFO - Socket Information: ('10.224.0.39', 8888)
2016-05-30 15:41:24,909 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 626, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'BlockingIOError: [Errno 11] Resource temporarily unavailable\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 626, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'KeyboardInterrupt\n']
2016-05-30 15:42:02,441 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 254, in PrepareSocket\n    UDPSocket.bind(UDPaddr)\n', 'TypeError: string or unicode text buffer expected, not NoneType\n']
2016-05-30 15:42:21,446 - root - INFO - Socket Information: ('10.224.0.39', 8888)
2016-05-30 15:45:51,160 - root - INFO - Socket Information: ('10.224.0.39', 8888)
2016-05-30 15:48:49,827 - root - INFO - Socket Information: ('10.224.0.39', 8888)
2016-05-30 15:56:38,918 - root - INFO - Socket Information: ('10.224.0.39', 8888)
2016-05-30 15:59:24,181 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:00:04,421 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 323, in PrepareMessage\n    logging.debug("Preparing Message for :" + destination)\n', "TypeError: Can't convert 'c_byte_Array_4' object to str implicitly\n"]
2016-05-30 16:00:04,424 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 548, in ChunkMessages\n    header.hop_count)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 323, in PrepareMessage\n    logging.debug("Preparing Message for :" + destination)\n', "TypeError: Can't convert 'c_byte_Array_4' object to str implicitly\n"]
2016-05-30 16:00:43,630 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 528, in Send_Message\n    logging.debug("Sent to: " + addr[0] +"=>" + addr[1])\n', "TypeError: Can't convert 'int' object to str implicitly\n"]
2016-05-30 16:00:44,402 - root - ERROR - Couldn't send messages...
2016-05-30 16:01:10,480 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:06:43,289 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 323, in PrepareMessage\n    logging.debug("Preparing Message for :" + bytearray(destination).hex().upper())\n', "TypeError: Can't convert 'c_byte_Array_4' object to str implicitly\n"]
2016-05-30 16:06:43,293 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 548, in ChunkMessages\n    header.hop_count)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 323, in PrepareMessage\n    logging.debug("Preparing Message for :" + bytearray(destination).hex().upper())\n', "TypeError: Can't convert 'c_byte_Array_4' object to str implicitly\n"]
2016-05-30 16:06:43,297 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 528, in Send_Message\n    logging.debug("Sent to: " + addr[0] +"=>" + addr[1])\n', "TypeError: Can't convert 'int' object to str implicitly\n"]
2016-05-30 16:06:43,299 - root - ERROR - Couldn't send messages...
2016-05-30 16:06:49,616 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 632, in recv_flag\n    pass\n', 'KeyboardInterrupt\n']
2016-05-30 16:07:00,078 - root - INFO - Socket Information: ('10.224.0.39', 8888)
2016-05-30 16:07:17,661 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:08:52,912 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 563, in ChunkMessages\n    logging.debug("Chunking completed with:" + len(MessageList) + "Packets.")\n', "TypeError: Can't convert 'int' object to str implicitly\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 523, in Send_Message\n    messagetosend = ChunkMessages(payload, header)\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 567, in ChunkMessages\n    logging.error(repr(traceback.format_exception(exc_type, exc_value,\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 567, in ChunkMessages\n    logging.error(repr(traceback.format_exception(exc_type, exc_value,\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 602, in trace_dispatch\n    self.do_wait_suspend(thread, frame, event, arg)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 69, in do_wait_suspend\n    self._args[0].do_wait_suspend(*args, **kwargs)\n', '  File "/home/raziel/Downloads/pycharm-community-2016.1.4/helpers/pydev/pydevd.py", line 712, in do_wait_suspend\n    time.sleep(0.01)\n', 'KeyboardInterrupt\n']
2016-05-30 16:08:52,913 - root - ERROR - Couldn't send messages...
2016-05-30 16:09:01,029 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 229, in Get_Port\n    temp = input(\'>>Port Number: \')\n', 'KeyboardInterrupt\n']
2016-05-30 16:09:01,032 - root - INFO - Because of Errors PORT 6666 is assigned.
2016-05-30 16:09:13,240 - root - INFO - Socket Information: ('10.224.0.39', 8888)
2016-05-30 16:09:25,656 - root - INFO - Neighboring Message is being prepared...
2016-05-30 16:09:25,660 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:10:52,672 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 528, in Send_Message\n    logging.debug("Sent to: " + addr[0] +"=>" + addr[1])\n', "TypeError: Can't convert 'int' object to str implicitly\n"]
2016-05-30 16:10:52,944 - root - ERROR - Couldn't send messages...
2016-05-30 16:11:18,432 - root - INFO - Socket Information: ('10.224.0.39', 8888)
2016-05-30 16:11:35,836 - root - INFO - Neighboring Message is being prepared...
2016-05-30 16:11:35,839 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:14:29,894 - root - INFO - Socket Information: ('10.224.0.39', 7777)
2016-05-30 16:14:41,887 - root - INFO - Neighboring Message is being prepared...
2016-05-30 16:14:41,890 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:14:49,910 - root - INFO - Unpacking Message Array...
2016-05-30 16:17:06,472 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 835, in Add_KeyIDTable\n    username = input(\'Enter Username for this IP>>\')\n', 'KeyboardInterrupt\n']
2016-05-30 16:17:06,477 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:17:28,035 - root - INFO - Socket Information: ('10.224.0.39', 7777)
2016-05-30 16:18:16,348 - root - INFO - Socket Information: ('10.224.0.39', 5555)
2016-05-30 16:18:25,083 - root - INFO - Neighboring Message is being prepared...
2016-05-30 16:18:25,087 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:18:33,111 - root - INFO - Unpacking Message Array...
2016-05-30 16:19:39,934 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 838, in Add_KeyIDTable\n    logging.debug(keyID_newline + "has been added to KeyID Table...")\n', "TypeError: unsupported operand type(s) for +: 'dict' and 'str'\n"]
2016-05-30 16:21:28,436 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:24:10,964 - root - INFO - Socket Information: ('10.224.0.39', 5555)
2016-05-30 16:24:21,296 - root - INFO - Neighboring Message is being prepared...
2016-05-30 16:24:21,300 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:24:37,588 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'BlockingIOError: [Errno 11] Resource temporarily unavailable\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'KeyboardInterrupt\n']
2016-05-30 16:24:55,786 - root - INFO - Socket Information: ('10.224.0.39', 5555)
2016-05-30 16:25:04,630 - root - INFO - Neighboring Message is being prepared...
2016-05-30 16:25:04,634 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:25:12,705 - root - INFO - Unpacking Message Array...
2016-05-30 16:25:57,760 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'BlockingIOError: [Errno 11] Resource temporarily unavailable\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 627, in recv_flag\n    data,addr = the_socket.recvfrom(buf)\n', 'KeyboardInterrupt\n']
2016-05-30 16:26:25,278 - root - INFO - Socket Information: ('10.224.0.39', 5555)
2016-05-30 16:26:36,835 - root - INFO - Neighboring Message is being prepared...
2016-05-30 16:26:36,839 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:26:44,890 - root - INFO - Unpacking Message Array...
2016-05-30 16:27:11,967 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:30:55,835 - root - INFO - Socket Information: ('10.224.0.39', 5555)
2016-05-30 16:31:05,309 - root - INFO - Neighboring Message is being prepared...
2016-05-30 16:31:05,315 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:31:13,800 - root - INFO - Unpacking Message Array...
2016-05-30 16:31:25,597 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:32:34,597 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 229, in Get_Port\n    temp = input(\'>>Port Number: \')\n', 'KeyboardInterrupt\n']
2016-05-30 16:32:34,599 - root - INFO - Because of Errors PORT 6666 is assigned.
2016-05-30 16:32:48,897 - root - INFO - Socket Information: ('10.224.0.39', 5555)
2016-05-30 16:33:02,271 - root - INFO - Neighboring Message is being prepared...
2016-05-30 16:33:02,274 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:33:10,425 - root - INFO - Unpacking Message Array...
2016-05-30 16:33:16,221 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:33:22,363 - root - INFO - NEIGHBORING ACK Message from EC8AF480 Processsed!.
2016-05-30 16:33:49,185 - root - WARNING - This UUID Already Exists
2016-05-30 16:35:22,617 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:36:22,087 - root - INFO - Unpacking Message Array...
2016-05-30 16:36:34,178 - root - INFO - NEIGHBORING ACK Message from EC8AF480 Processsed!.
2016-05-30 16:37:51,470 - root - INFO - SessionKey Entry cannot be Found...Initialising AUTH Protocol...
2016-05-30 16:37:52,621 - root - INFO - Setting Passphrase.. This Procedure is one time only...
2016-05-30 16:37:56,531 - root - INFO - PassPhrase is set!
2016-05-30 16:38:16,435 - root - INFO - Auth Payload is being prepared...
2016-05-30 16:38:16,438 - root - INFO - PGP Challenge Encryption Process started...
2016-05-30 16:38:16,444 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 435, in PGPEncMsg\n    encrypted_challenge = gpg.encrypt(challenge, rec_id).data\n', "NameError: name 'gpg' is not defined\n"]
2016-05-30 16:38:16,449 - root - ERROR - ['Traceback (most recent call last):\n', '  File "/media/raziel/Raziel-HDD/Work/NetworkProtocolDesign/Nesli/ITC8061/ChatApp/Utils.py", line 420, in PrepareAuthenticationPayload\n    AuthMessagetoSend, challenge = PGPEncMsg(rec_id, myPP)\n', "TypeError: 'NoneType' object is not iterable\n"]
2016-05-30 16:38:16,454 - root - INFO - Message Sending Protocol Initialized...
2016-05-30 16:38:16,464 - root - INFO - Auth Message Sent to: EC8AF480
2016-05-30 16:38:42,893 - root - INFO - AUTH Sent to: EC8AF480
